title: "AWS SAMによるサーバレスアプリケーション開発入門"
summary: "AWS SAMを使ったサーバレスアプリケーションの開発方法を学ぶための入門書です。まだ執筆中で、随時加筆していきます。"
topics: ["AWS", "SAM", "Serverless", "Lambda", "API Gateway", "SQS"]
published: true
price: 0 # 有料の場合200〜5000
toc_depth: 2
